name: alok
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  simple_animations: ^1.3.3
  http:
  toast: ^0.1.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.3.0
  cupertino_icons: ^1.0.0
  file_picker: ^2.0.7
  flutter_dropdown: ^0.0.8
  giffy_dialog: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner:

flutter:
  uses-material-design: true
  assets:
   - assets/images/